[default_session]
startup_command = "source ~/.config/sesh/init.sh"

[[session]]
name = "MyHome"
path = "~/"

[[session]]
name = "ZSH config"
path = "~/dotfiles/zsh/"
startup_command = "nvim .zshrc"
preview_command = "lsd --tree"

[[session]]
name = "tmux config"
path = "~/dotfiles/tmux/"
startup_command = "nvim .tmux.conf"

[[session]]
name = "nvim config"
path = "~/dotfiles/nvim/.config/nvim/"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "Dot Files"
path = "~/dotfiles/"

[[session]]
name = "Ansible"
path = "~/dev/ansible/balcones"
# startup_command = "nvim ./config"

[[session]]
name = "SSH configs"
path = "~/.ssh/"
startup_command = "nvim ./config"

[[session]]
name = "Sesh Configs"
path = "~/.config/sesh/"
startup_command = "nvim ./sesh.toml"

[[session]]
name = "Obsidian"
path = "~/Nextcloud/Obsidian/"
startup_command = "nvim"

[[session]]
name = "oci-cli"
path = "~/dev/oci/"

