[default_session]
startup_command = "source init.sh || pyfiglet '$current_dir'"
# startup_command = "nvim -c ':Telescope find_files'"
# echo "        Current Project: $(basename "$PWD")

[[session]]
name = "MyHome"
path = "~/"
startup_command = "pyfiglet 'Welcome to my home'"

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "ZSH config"
path = "~/"
startup_command = "nvim .zshrc"

[[session]]
name = "tmux config"
path = "~/"
startup_command = "nvim .tmux.conf"

[[session]]
name = "nvim config"
path = "~/.config/nvim/"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "Dot Files"
path = "~/dotfiles/"

[[session]]
name = "Sesh Configs"
path = "~/.config/sesh/"
startup_command = "nvim ./sesh.toml"

[[session]]
name = "Obsidian"
path = "~/Nextcloud/Obsidian/"
startup_command = "nvim"

[[session]]
name = "SSH config"
path = "~/.ssh/"
startup_command = "nvim -c ':Telescope find_files'"
