# Obtener terminaciones del editor basado en el esquema de configuración
"$schema" = 'https://starship.rs/config-schema.json'

# Inserta una línea en blanco entre las instrucciones del intérprete de comandos
add_newline = true

# Reemplaza el símbolo '❯' en el prompt con ''➜'
[character] # El nombre del módulo que estamos configurando es 'character'
success_symbol = '[➜](bold white)'
error_symbol   = '[➜](bold red)'
vicmd_symbol   = '[⇐](green)'

# Desactiva el módulo del paquete, ocultándolo del prompt completamente
#[package]
#disabled = true
